version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /apps/docker/frigate/config.yml:/config/config.yml:ro
      - /apps/docker/frigate:/config
      - /home/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_MQTT_USER: "XXXXXXXXXXXX"
      FRIGATE_MQTT_PASSWORD: "XXXXXXXXXXXX"
      FRIGATE_GO2RTC_RTSP_USERNAME: "XXXXXXXXX"
      FRIGATE_GO2RTC_RTSP_PASSWORD: "XXXXXXXXXXXXXXX"
      UID: "1000"
      GID: "1011"
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp