---
version: "3.8"
services:

  readarr:
    container_name: readarr
    working_dir: /apps/docker/readarr
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=1000
      - PGID=1011
      - TZ=America/New_York
    volumes:
      - /apps/docker/readarr:/config
      - /home:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  radarr:
    container_name: radarr
    working_dir: /apps/docker/radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1011
      - TZ=America/New_York
    volumes:
      - /apps/docker/radarr:/config
      - /home:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    working_dir: /apps/docker/sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1011
      - TZ=America/New_York
    volumes:
      - /apps/docker/sonarr:/config
      - /home:/data
    ports:
      - 8136:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1011
      - TZ=America/New_York
    volumes:
      - /apps/docker/prowlarr:/config
      - /home:/data
    ports:
      - 9696:9696
    restart: unless-stopped
  
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1011
      - TZ=America/New_York
    volumes:
      - /apps/docker/bazarr:/config
      - /home/media/movies:/movies
      - /home/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped